# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'information.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Information(object):
    def setupUi(self, Information):
        Information.setObjectName("Information")
        Information.resize(926, 841)
        self.centralwidget = QtWidgets.QWidget(Information)
        self.centralwidget.setObjectName("centralwidget")
        self.IButtonYes = QtWidgets.QPushButton(self.centralwidget)
        self.IButtonYes.setGeometry(QtCore.QRect(80, 730, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IButtonYes.setFont(font)
        self.IButtonYes.setObjectName("IButtonYes")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 510, 198, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(50, 320, 461, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 0, 241, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.horizontalLayout.addWidget(self.lineName)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 80, 241, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineGender = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineGender.setFont(font)
        self.lineGender.setObjectName("lineGender")
        self.horizontalLayout_2.addWidget(self.lineGender)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 160, 241, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.lineage = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineage.setFont(font)
        self.lineage.setObjectName("lineage")
        self.horizontalLayout_3.addWidget(self.lineage)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(520, 0, 241, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.linePhone = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.linePhone.setFont(font)
        self.linePhone.setObjectName("linePhone")
        self.horizontalLayout_4.addWidget(self.linePhone)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(520, 80, 241, 71))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.lineAdress = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineAdress.setFont(font)
        self.lineAdress.setObjectName("lineAdress")
        self.horizontalLayout_5.addWidget(self.lineAdress)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(520, 160, 351, 71))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.lineIdcard = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineIdcard.setFont(font)
        self.lineIdcard.setObjectName("lineIdcard")
        self.horizontalLayout_6.addWidget(self.lineIdcard)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 240, 241, 71))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.lineSymptom = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineSymptom.setFont(font)
        self.lineSymptom.setObjectName("lineSymptom")
        self.horizontalLayout_7.addWidget(self.lineSymptom)
        self.IButtonInquire = QtWidgets.QPushButton(self.centralwidget)
        self.IButtonInquire.setGeometry(QtCore.QRect(290, 730, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IButtonInquire.setFont(font)
        self.IButtonInquire.setObjectName("IButtonInquire")
        self.IButtonOut = QtWidgets.QPushButton(self.centralwidget)
        self.IButtonOut.setGeometry(QtCore.QRect(710, 730, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IButtonOut.setFont(font)
        self.IButtonOut.setObjectName("IButtonOut")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(50, 550, 461, 161))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.option = QtWidgets.QListWidget(self.centralwidget)
        self.option.setGeometry(QtCore.QRect(50, 320, 241, 151))
        self.option.setObjectName("option")
        Information.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Information)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 25))
        self.menubar.setObjectName("menubar")
        Information.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Information)
        self.statusbar.setObjectName("statusbar")
        Information.setStatusBar(self.statusbar)

        self.retranslateUi(Information)
        QtCore.QMetaObject.connectSlotsByName(Information)

    def retranslateUi(self, Information):
        _translate = QtCore.QCoreApplication.translate
        Information.setWindowTitle(_translate("Information", "MainWindow"))
        self.IButtonYes.setText(_translate("Information", "确定"))
        self.label_8.setText(_translate("Information", "望闻问切经带"))
        self.label.setText(_translate("Information", "名字"))
        self.label_9.setText(_translate("Information", "性别"))
        self.label_10.setText(_translate("Information", "年龄"))
        self.label_11.setText(_translate("Information", "手机"))
        self.label_12.setText(_translate("Information", "住址"))
        self.label_13.setText(_translate("Information", "身份证"))
        self.label_14.setText(_translate("Information", "主诉"))
        self.IButtonInquire.setText(_translate("Information", "查询"))
        self.IButtonOut.setText(_translate("Information", "退出"))

