# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inquire.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Inquire(object):
    def setupUi(self, Inquire):
        Inquire.setObjectName("Inquire")
        Inquire.resize(782, 754)
        self.centralwidget = QtWidgets.QWidget(Inquire)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 90, 241, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineName.setFont(font)
        self.lineName.setObjectName("lineName")
        self.horizontalLayout.addWidget(self.lineName)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(440, 90, 241, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.linePhone = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.linePhone.setFont(font)
        self.linePhone.setObjectName("linePhone")
        self.horizontalLayout_4.addWidget(self.linePhone)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(70, 180, 351, 71))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.lineIdcard = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineIdcard.setFont(font)
        self.lineIdcard.setObjectName("lineIdcard")
        self.horizontalLayout_6.addWidget(self.lineIdcard)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ButtonYes = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonYes.setGeometry(QtCore.QRect(110, 610, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ButtonYes.setFont(font)
        self.ButtonYes.setObjectName("ButtonYes")
        self.ButtonOut = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonOut.setGeometry(QtCore.QRect(440, 610, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ButtonOut.setFont(font)
        self.ButtonOut.setObjectName("ButtonOut")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(60, 270, 681, 291))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(112)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        Inquire.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Inquire)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 25))
        self.menubar.setObjectName("menubar")
        Inquire.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Inquire)
        self.statusbar.setObjectName("statusbar")
        Inquire.setStatusBar(self.statusbar)

        self.retranslateUi(Inquire)
        QtCore.QMetaObject.connectSlotsByName(Inquire)

    def retranslateUi(self, Inquire):
        _translate = QtCore.QCoreApplication.translate
        Inquire.setWindowTitle(_translate("Inquire", "MainWindow"))
        self.label.setText(_translate("Inquire", "名字"))
        self.label_11.setText(_translate("Inquire", "手机"))
        self.label_13.setText(_translate("Inquire", "身份证"))
        self.label_2.setText(_translate("Inquire", "检索条件"))
        self.ButtonYes.setText(_translate("Inquire", "确定"))
        self.ButtonOut.setText(_translate("Inquire", "退出"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Inquire", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Inquire", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Inquire", "性别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Inquire", "年龄"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Inquire", "手机"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Inquire", "身份证"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Inquire", "地址"))

